// Package accountfile keeps household YouTube sessions on disk.
//
// Files rather than the database, and the reason is what these are. A
// cookies.txt is a live Google session: whoever reads one is signed in as that
// person, everywhere, not merely on YouTube. In Postgres it would be in every
// backup, in every `SELECT *` somebody runs while debugging, and in the query
// log. On disk it is one path with one mode, and the only code that opens it is
// the code building a yt-dlp command line.
package accountfile

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"sync"
	"time"

	"github.com/lucnguyen/local-youtube/services/ingest/internal/domain"
)

// Store is the cookie directory and its registry.
type Store struct {
	dir string
	mu  sync.Mutex
}

func New(dir string) *Store {
	return &Store{dir: dir}
}

func (s *Store) cookiePath(userID string) string {
	// The id is generated by the gateway from a name and is already restricted
	// to letters and digits, but this is a path built from input, so it is
	// reduced to a base name regardless. A profile id is never a directory.
	return filepath.Join(s.dir, filepath.Base(userID)+".txt")
}

func (s *Store) registryPath() string {
	return filepath.Join(s.dir, "accounts.json")
}

// ensureDir creates the directory only the owner can enter.
//
// 0700 rather than 0755, and it matters more than the file mode does: a
// readable directory tells anybody with a shell on this machine exactly which
// accounts exist and where their sessions are.
func (s *Store) ensureDir() error {
	return os.MkdirAll(s.dir, 0o700)
}

func (s *Store) loadRegistry() map[string]domain.Account {
	out := map[string]domain.Account{}
	raw, err := os.ReadFile(s.registryPath())
	if err != nil || len(raw) == 0 {
		return out
	}
	var saved []domain.Account
	if err := json.Unmarshal(raw, &saved); err != nil {
		// Same rule the gateway's settings files follow: a file somebody has
		// been editing by hand must not stop the pass. The cookies themselves
		// are not in here, so the worst case is losing the "last scanned" note.
		return out
	}
	for _, a := range saved {
		if a.UserID != "" {
			out[a.UserID] = a
		}
	}
	return out
}

func (s *Store) saveRegistry(entries map[string]domain.Account) error {
	list := make([]domain.Account, 0, len(entries))
	for _, a := range entries {
		list = append(list, a)
	}
	sort.Slice(list, func(i, j int) bool { return list[i].UserID < list[j].UserID })

	raw, err := json.MarshalIndent(list, "", "  ")
	if err != nil {
		return err
	}
	if err := s.ensureDir(); err != nil {
		return err
	}
	return os.WriteFile(s.registryPath(), raw, 0o600)
}

func (s *Store) Save(_ context.Context, userID, label, cookies string) error {
	if userID == "" {
		return fmt.Errorf("%w: user_id is required", domain.ErrInvalid)
	}
	// Validated before anything is written, so a bad paste cannot replace a
	// working session with a broken one.
	if err := domain.ValidateCookies(cookies); err != nil {
		return err
	}
	if err := s.ensureDir(); err != nil {
		return err
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	if err := os.WriteFile(s.cookiePath(userID), []byte(cookies), 0o600); err != nil {
		return err
	}

	entries := s.loadRegistry()
	existing, known := entries[userID]
	entry := domain.Account{
		UserID:  userID,
		Label:   label,
		AddedAt: time.Now(),
		State:   domain.AccountOK,
	}
	if known {
		entry.AddedAt = existing.AddedAt
		if label == "" {
			entry.Label = existing.Label
		}
	}
	// A fresh paste clears the failure count outright. Re-pasting *is* the
	// answer to an expired session, and carrying the old count forward would
	// expire the new one on its first bad hour.
	entries[userID] = entry
	return s.saveRegistry(entries)
}

func (s *Store) Remove(_ context.Context, userID string) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	if err := os.Remove(s.cookiePath(userID)); err != nil && !os.IsNotExist(err) {
		return err
	}
	entries := s.loadRegistry()
	delete(entries, userID)
	return s.saveRegistry(entries)
}

func (s *Store) List(_ context.Context) ([]domain.Account, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	entries := s.loadRegistry()
	list := make([]domain.Account, 0, len(entries))
	for _, a := range entries {
		// The registry can outlive the file — somebody deleting a cookies.txt
		// by hand is a supported way to revoke access, and it must not leave
		// the screen claiming the account still works.
		if _, err := os.Stat(s.cookiePath(a.UserID)); err != nil {
			a.State = domain.AccountNeverSet
		}
		list = append(list, a)
	}
	sort.Slice(list, func(i, j int) bool { return list[i].UserID < list[j].UserID })
	return list, nil
}

func (s *Store) CookiePath(_ context.Context, userID string) (string, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	entries := s.loadRegistry()
	if entry, ok := entries[userID]; ok && entry.State == domain.AccountExpired {
		// An expired session is not retried. Replaying a dead cookie every hour
		// is how a blocked address becomes a banned account.
		return "", domain.ErrNoAccount
	}
	path := s.cookiePath(userID)
	if _, err := os.Stat(path); err != nil {
		return "", domain.ErrNoAccount
	}
	return path, nil
}

func (s *Store) Record(_ context.Context, userID, result string, authFailed bool) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	entries := s.loadRegistry()
	entry, ok := entries[userID]
	if !ok {
		entry = domain.Account{UserID: userID, AddedAt: time.Now()}
	}
	entry.LastScanAt = time.Now()
	entry.LastResult = result

	if authFailed {
		entry.Failures++
		if entry.Failures >= domain.AccountFailureLimit {
			entry.State = domain.AccountExpired
		}
	} else {
		// A pass that worked clears the count rather than decrementing it. The
		// limit is about failures *in a row*, and one good pass says the
		// session is alive whatever happened before it.
		entry.Failures = 0
		entry.State = domain.AccountOK
	}
	entries[userID] = entry
	return s.saveRegistry(entries)
}
